name: MAE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pip=24.2
  - ipykernel=6.29.5
  - ipython=8.12.2
  - matplotlib-inline=0.1.7
  - psutil=6.0.0
  - typing_extensions=4.12.2
  - _libgcc_mutex=0.1
  - ca-certificates=2026.1.4
  - openssl=3.6.0
  - sqlite=3.51.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.0.1+cu118
      - torchvision==0.15.2+cu118
      - torchaudio==2.0.2+cu118
      - numpy==1.24.4
      - timm==0.4.12
      - matplotlib==3.7.5
      - tensorboard==2.11.0
      - pillow==10.4.0
      - scipy==1.10.1
      - submitit==1.5.4
      - requests==2.32.4
      - fsspec==2023.6.0
      - pyyaml
